export const countries = [
  {
    value: "AF",
    label: "🇦🇫 Afghanistan",
    phoneCode: "+93",
    currencyCode: "AFN",
    countryCode: "AF",
  },
  {
    value: "AL",
    label: "🇦🇱 Albania",
    phoneCode: "+355",
    currencyCode: "ALL",
    countryCode: "AL",
  },
  {
    value: "DZ",
    label: "🇩🇿 Algeria",
    phoneCode: "+213",
    currencyCode: "DZD",
    countryCode: "DZ",
  },
  {
    value: "AS",
    label: "🇦🇸 American Samoa",
    phoneCode: "+1684",
    currencyCode: "USD",
    countryCode: "AS",
  },
  {
    value: "AD",
    label: "🇦🇩 Andorra",
    phoneCode: "+376",
    currencyCode: "EUR",
    countryCode: "AD",
  },
  {
    value: "AO",
    label: "🇦🇴 Angola",
    phoneCode: "+244",
    currencyCode: "AOA",
    countryCode: "AO",
  },
  {
    value: "AI",
    label: "🇦🇮 Anguilla",
    phoneCode: "+1264",
    currencyCode: "XCD",
    countryCode: "AI",
  },
  {
    value: "AQ",
    label: "🇦🇶 Antarctica",
    phoneCode: "+672",
    currencyCode: "USD",
    countryCode: "AQ",
  },
  {
    value: "AG",
    label: "🇦🇬 Antigua and Barbuda",
    phoneCode: "+1268",
    currencyCode: "XCD",
    countryCode: "AG",
  },
  {
    value: "AR",
    label: "🇦🇷 Argentina",
    phoneCode: "+54",
    currencyCode: "ARS",
    countryCode: "AR",
  },
  {
    value: "AM",
    label: "🇦🇲 Armenia",
    phoneCode: "+374",
    currencyCode: "AMD",
    countryCode: "AM",
  },
  {
    value: "AW",
    label: "🇦🇼 Aruba",
    phoneCode: "+297",
    currencyCode: "AWG",
    countryCode: "AW",
  },
  {
    value: "AU",
    label: "🇦🇺 Australia",
    phoneCode: "+61",
    currencyCode: "AUD",
    countryCode: "AU",
  },
  {
    value: "AT",
    label: "🇦🇹 Austria",
    phoneCode: "+43",
    currencyCode: "EUR",
    countryCode: "AT",
  },
  {
    value: "AZ",
    label: "🇦🇿 Azerbaijan",
    phoneCode: "+994",
    currencyCode: "AZN",
    countryCode: "AZ",
  },
  {
    value: "BS",
    label: "🇧🇸 Bahamas",
    phoneCode: "+1242",
    currencyCode: "BSD",
    countryCode: "BS",
  },
  {
    value: "BH",
    label: "🇧🇭 Bahrain",
    phoneCode: "+973",
    currencyCode: "BHD",
    countryCode: "BH",
  },
  {
    value: "BD",
    label: "🇧🇩 Bangladesh",
    phoneCode: "+880",
    currencyCode: "BDT",
    countryCode: "BD",
  },
  {
    value: "BB",
    label: "🇧🇧 Barbados",
    phoneCode: "+1246",
    currencyCode: "BBD",
    countryCode: "BB",
  },
  {
    value: "BY",
    label: "🇧🇾 Belarus",
    phoneCode: "+375",
    currencyCode: "BYN",
    countryCode: "BY",
  },
  {
    value: "BE",
    label: "🇧🇪 Belgium",
    phoneCode: "+32",
    currencyCode: "EUR",
    countryCode: "BE",
  },
  {
    value: "BZ",
    label: "🇧🇿 Belize",
    phoneCode: "+501",
    currencyCode: "BZD",
    countryCode: "BZ",
  },
  {
    value: "BJ",
    label: "🇧🇯 Benin",
    phoneCode: "+229",
    currencyCode: "XOF",
    countryCode: "BJ",
  },
  {
    value: "BM",
    label: "🇧🇲 Bermuda",
    phoneCode: "+1441",
    currencyCode: "BMD",
    countryCode: "BM",
  },
  {
    value: "BT",
    label: "🇧🇹 Bhutan",
    phoneCode: "+975",
    currencyCode: "BTN",
    countryCode: "BT",
  },
  {
    value: "BO",
    label: "🇧🇴 Bolivia",
    phoneCode: "+591",
    currencyCode: "BOB",
    countryCode: "BO",
  },
  {
    value: "BA",
    label: "🇧🇦 Bosnia and Herzegovina",
    phoneCode: "+387",
    currencyCode: "BAM",
    countryCode: "BA",
  },
  {
    value: "BW",
    label: "🇧🇼 Botswana",
    phoneCode: "+267",
    currencyCode: "BWP",
    countryCode: "BW",
  },
  {
    value: "BR",
    label: "🇧🇷 Brazil",
    phoneCode: "+55",
    currencyCode: "BRL",
    countryCode: "BR",
  },
  {
    value: "IO",
    label: "🇮🇴 British Indian Ocean Territory",
    phoneCode: "+246",
    currencyCode: "USD",
    countryCode: "IO",
  },
  {
    value: "BN",
    label: "🇧🇳 Brunei",
    phoneCode: "+673",
    currencyCode: "BND",
    countryCode: "BN",
  },
  {
    value: "BG",
    label: "🇧🇬 Bulgaria",
    phoneCode: "+359",
    currencyCode: "BGN",
    countryCode: "BG",
  },
  {
    value: "BF",
    label: "🇧🇫 Burkina Faso",
    phoneCode: "+226",
    currencyCode: "XOF",
    countryCode: "BF",
  },
  {
    value: "BI",
    label: "🇧🇮 Burundi",
    phoneCode: "+257",
    currencyCode: "BIF",
    countryCode: "BI",
  },
  {
    value: "CV",
    label: "🇨🇻 Cape Verde",
    phoneCode: "+238",
    currencyCode: "CVE",
    countryCode: "CV",
  },
  {
    value: "KH",
    label: "🇰🇭 Cambodia",
    phoneCode: "+855",
    currencyCode: "KHR",
    countryCode: "KH",
  },
  {
    value: "CM",
    label: "🇨🇲 Cameroon",
    phoneCode: "+237",
    currencyCode: "XAF",
    countryCode: "CM",
  },
  {
    value: "CA",
    label: "🇨🇦 Canada",
    phoneCode: "+1",
    currencyCode: "CAD",
    countryCode: "CA",
  },
  {
    value: "KY",
    label: "🇰🇾 Cayman Islands",
    phoneCode: "+1345",
    currencyCode: "KYD",
    countryCode: "KY",
  },
  {
    value: "CF",
    label: "🇨🇫 Central African Republic",
    phoneCode: "+236",
    currencyCode: "XAF",
    countryCode: "CF",
  },
  {
    value: "TD",
    label: "🇹🇩 Chad",
    phoneCode: "+235",
    currencyCode: "XAF",
    countryCode: "TD",
  },
  {
    value: "CL",
    label: "🇨🇱 Chile",
    phoneCode: "+56",
    currencyCode: "CLP",
    countryCode: "CL",
  },
  {
    value: "CN",
    label: "🇨🇳 China",
    phoneCode: "+86",
    currencyCode: "CNY",
    countryCode: "CN",
  },
  {
    value: "CX",
    label: "🇨🇽 Christmas Island",
    phoneCode: "+61",
    currencyCode: "AUD",
    countryCode: "CX",
  },
  {
    value: "CC",
    label: "🇨🇨 Cocos Islands",
    phoneCode: "+61",
    currencyCode: "AUD",
    countryCode: "CC",
  },
  {
    value: "CO",
    label: "🇨🇴 Colombia",
    phoneCode: "+57",
    currencyCode: "COP",
    countryCode: "CO",
  },
  {
    value: "KM",
    label: "🇰🇲 Comoros",
    phoneCode: "+269",
    currencyCode: "KMF",
    countryCode: "KM",
  },
  {
    value: "CG",
    label: "🇨🇬 Congo",
    phoneCode: "+242",
    currencyCode: "XAF",
    countryCode: "CG",
  },
  {
    value: "CD",
    label: "🇨🇩 Congo (DRC)",
    phoneCode: "+243",
    currencyCode: "CDF",
    countryCode: "CD",
  },
  {
    value: "CK",
    label: "🇨🇰 Cook Islands",
    phoneCode: "+682",
    currencyCode: "NZD",
    countryCode: "CK",
  },
  {
    value: "CR",
    label: "🇨🇷 Costa Rica",
    phoneCode: "+506",
    currencyCode: "CRC",
    countryCode: "CR",
  },
  {
    value: "CI",
    label: "🇨🇮 Côte d'Ivoire",
    phoneCode: "+225",
    currencyCode: "XOF",
    countryCode: "CI",
  },
  {
    value: "HR",
    label: "🇭🇷 Croatia",
    phoneCode: "+385",
    currencyCode: "EUR",
    countryCode: "HR",
  },
  {
    value: "CU",
    label: "🇨🇺 Cuba",
    phoneCode: "+53",
    currencyCode: "CUP",
    countryCode: "CU",
  },
  {
    value: "CW",
    label: "🇨🇼 Curaçao",
    phoneCode: "+599",
    currencyCode: "ANG",
    countryCode: "CW",
  },
  {
    value: "CY",
    label: "🇨🇾 Cyprus",
    phoneCode: "+357",
    currencyCode: "EUR",
    countryCode: "CY",
  },
  {
    value: "CZ",
    label: "🇨🇿 Czech Republic",
    phoneCode: "+420",
    currencyCode: "CZK",
    countryCode: "CZ",
  },
  {
    value: "DK",
    label: "🇩🇰 Denmark",
    phoneCode: "+45",
    currencyCode: "DKK",
    countryCode: "DK",
  },
  {
    value: "DJ",
    label: "🇩🇯 Djibouti",
    phoneCode: "+253",
    currencyCode: "DJF",
    countryCode: "DJ",
  },
  {
    value: "DM",
    label: "🇩🇲 Dominica",
    phoneCode: "+1767",
    currencyCode: "XCD",
    countryCode: "DM",
  },
  {
    value: "DO",
    label: "🇩🇴 Dominican Republic",
    phoneCode: "+1",
    currencyCode: "DOP",
    countryCode: "DO",
  },
  {
    value: "EC",
    label: "🇪🇨 Ecuador",
    phoneCode: "+593",
    currencyCode: "USD",
    countryCode: "EC",
  },
  {
    value: "EG",
    label: "🇪🇬 Egypt",
    phoneCode: "+20",
    currencyCode: "EGP",
    countryCode: "EG",
  },
  {
    value: "SV",
    label: "🇸🇻 El Salvador",
    phoneCode: "+503",
    currencyCode: "USD",
    countryCode: "SV",
  },
  {
    value: "GQ",
    label: "🇬🇶 Equatorial Guinea",
    phoneCode: "+240",
    currencyCode: "XAF",
    countryCode: "GQ",
  },
  {
    value: "ER",
    label: "🇪🇷 Eritrea",
    phoneCode: "+291",
    currencyCode: "ERN",
    countryCode: "ER",
  },
  {
    value: "EE",
    label: "🇪🇪 Estonia",
    phoneCode: "+372",
    currencyCode: "EUR",
    countryCode: "EE",
  },
  {
    value: "SZ",
    label: "🇸🇿 Eswatini",
    phoneCode: "+268",
    currencyCode: "SZL",
    countryCode: "SZ",
  },
  {
    value: "ET",
    label: "🇪🇹 Ethiopia",
    phoneCode: "+251",
    currencyCode: "ETB",
    countryCode: "ET",
  },
  {
    value: "FK",
    label: "🇫🇰 Falkland Islands",
    phoneCode: "+500",
    currencyCode: "FKP",
    countryCode: "FK",
  },
  {
    value: "FO",
    label: "🇫🇴 Faroe Islands",
    phoneCode: "+298",
    currencyCode: "DKK",
    countryCode: "FO",
  },
  {
    value: "FJ",
    label: "🇫🇯 Fiji",
    phoneCode: "+679",
    currencyCode: "FJD",
    countryCode: "FJ",
  },
  {
    value: "FI",
    label: "🇫🇮 Finland",
    phoneCode: "+358",
    currencyCode: "EUR",
    countryCode: "FI",
  },
  {
    value: "FR",
    label: "🇫🇷 France",
    phoneCode: "+33",
    currencyCode: "EUR",
    countryCode: "FR",
  },
  {
    value: "GF",
    label: "🇬🇫 French Guiana",
    phoneCode: "+594",
    currencyCode: "EUR",
    countryCode: "GF",
  },
  {
    value: "PF",
    label: "🇵🇫 French Polynesia",
    phoneCode: "+689",
    currencyCode: "XPF",
    countryCode: "PF",
  },
  {
    value: "TF",
    label: "🇹🇫 French Southern Territories",
    phoneCode: "+262",
    currencyCode: "EUR",
    countryCode: "TF",
  },
  {
    value: "GA",
    label: "🇬🇦 Gabon",
    phoneCode: "+241",
    currencyCode: "XAF",
    countryCode: "GA",
  },
  {
    value: "GM",
    label: "🇬🇲 Gambia",
    phoneCode: "+220",
    currencyCode: "GMD",
    countryCode: "GM",
  },
  {
    value: "GE",
    label: "🇬🇪 Georgia",
    phoneCode: "+995",
    currencyCode: "GEL",
    countryCode: "GE",
  },
  {
    value: "DE",
    label: "🇩🇪 Germany",
    phoneCode: "+49",
    currencyCode: "EUR",
    countryCode: "DE",
  },
  {
    value: "GH",
    label: "🇬🇭 Ghana",
    phoneCode: "+233",
    currencyCode: "GHS",
    countryCode: "GH",
  },
  {
    value: "GI",
    label: "🇬🇮 Gibraltar",
    phoneCode: "+350",
    currencyCode: "GIP",
    countryCode: "GI",
  },
  {
    value: "GR",
    label: "🇬🇷 Greece",
    phoneCode: "+30",
    currencyCode: "EUR",
    countryCode: "GR",
  },
  {
    value: "GL",
    label: "🇬🇱 Greenland",
    phoneCode: "+299",
    currencyCode: "DKK",
    countryCode: "GL",
  },
  {
    value: "GD",
    label: "🇬🇩 Grenada",
    phoneCode: "+1473",
    currencyCode: "XCD",
    countryCode: "GD",
  },
  {
    value: "GP",
    label: "🇬🇵 Guadeloupe",
    phoneCode: "+590",
    currencyCode: "EUR",
    countryCode: "GP",
  },
  {
    value: "GU",
    label: "🇬🇺 Guam",
    phoneCode: "+1671",
    currencyCode: "USD",
    countryCode: "GU",
  },
  {
    value: "GT",
    label: "🇬🇹 Guatemala",
    phoneCode: "+502",
    currencyCode: "GTQ",
    countryCode: "GT",
  },
  {
    value: "GG",
    label: "🇬🇬 Guernsey",
    phoneCode: "+44",
    currencyCode: "GBP",
    countryCode: "GG",
  },
  {
    value: "GN",
    label: "🇬🇳 Guinea",
    phoneCode: "+224",
    currencyCode: "GNF",
    countryCode: "GN",
  },
  {
    value: "GW",
    label: "🇬🇼 Guinea-Bissau",
    phoneCode: "+245",
    currencyCode: "XOF",
    countryCode: "GW",
  },
  {
    value: "GY",
    label: "🇬🇾 Guyana",
    phoneCode: "+592",
    currencyCode: "GYD",
    countryCode: "GY",
  },
  {
    value: "HT",
    label: "🇭🇹 Haiti",
    phoneCode: "+509",
    currencyCode: "HTG",
    countryCode: "HT",
  },
  {
    value: "HM",
    label: "🇭🇲 Heard Island and McDonald Islands",
    phoneCode: "+672",
    currencyCode: "AUD",
    countryCode: "HM",
  },
  {
    value: "VA",
    label: "🇻🇦 Holy See",
    phoneCode: "+379",
    currencyCode: "EUR",
    countryCode: "VA",
  },
  {
    value: "HN",
    label: "🇭🇳 Honduras",
    phoneCode: "+504",
    currencyCode: "HNL",
    countryCode: "HN",
  },
  {
    value: "HK",
    label: "🇭🇰 Hong Kong",
    phoneCode: "+852",
    currencyCode: "HKD",
    countryCode: "HK",
  },
  {
    value: "HU",
    label: "🇭🇺 Hungary",
    phoneCode: "+36",
    currencyCode: "HUF",
    countryCode: "HU",
  },
  {
    value: "IS",
    label: "🇮🇸 Iceland",
    phoneCode: "+354",
    currencyCode: "ISK",
    countryCode: "IS",
  },
  {
    value: "IN",
    label: "🇮🇳 India",
    phoneCode: "+91",
    currencyCode: "INR",
    countryCode: "IN",
  },
  {
    value: "ID",
    label: "🇮🇩 Indonesia",
    phoneCode: "+62",
    currencyCode: "IDR",
    countryCode: "ID",
  },
  {
    value: "IR",
    label: "🇮🇷 Iran",
    phoneCode: "+98",
    currencyCode: "IRR",
    countryCode: "IR",
  },
  {
    value: "IQ",
    label: "🇮🇶 Iraq",
    phoneCode: "+964",
    currencyCode: "IQD",
    countryCode: "IQ",
  },
  {
    value: "IE",
    label: "🇮🇪 Ireland",
    phoneCode: "+353",
    currencyCode: "EUR",
    countryCode: "IE",
  },
  {
    value: "IM",
    label: "🇮🇲 Isle of Man",
    phoneCode: "+44",
    currencyCode: "GBP",
    countryCode: "IM",
  },
  {
    value: "IL",
    label: "🇮🇱 Israel",
    phoneCode: "+972",
    currencyCode: "ILS",
    countryCode: "IL",
  },
  {
    value: "IT",
    label: "🇮🇹 Italy",
    phoneCode: "+39",
    currencyCode: "EUR",
    countryCode: "IT",
  },
  {
    value: "JM",
    label: "🇯🇲 Jamaica",
    phoneCode: "+1876",
    currencyCode: "JMD",
    countryCode: "JM",
  },
  {
    value: "JP",
    label: "🇯🇵 Japan",
    phoneCode: "+81",
    currencyCode: "JPY",
    countryCode: "JP",
  },
  {
    value: "JE",
    label: "🇯🇪 Jersey",
    phoneCode: "+44",
    currencyCode: "GBP",
    countryCode: "JE",
  },
  {
    value: "JO",
    label: "🇯🇴 Jordan",
    phoneCode: "+962",
    currencyCode: "JOD",
    countryCode: "JO",
  },
  {
    value: "KZ",
    label: "🇰🇿 Kazakhstan",
    phoneCode: "+7",
    currencyCode: "KZT",
    countryCode: "KZ",
  },
  {
    value: "KE",
    label: "🇰🇪 Kenya",
    phoneCode: "+254",
    currencyCode: "KES",
    countryCode: "KE",
  },
  {
    value: "KI",
    label: "🇰🇮 Kiribati",
    phoneCode: "+686",
    currencyCode: "AUD",
    countryCode: "KI",
  },
  {
    value: "KP",
    label: "🇰🇵 North Korea",
    phoneCode: "+850",
    currencyCode: "KPW",
    countryCode: "KP",
  },
  {
    value: "KR",
    label: "🇰🇷 South Korea",
    phoneCode: "+82",
    currencyCode: "KRW",
    countryCode: "KR",
  },
  {
    value: "KW",
    label: "🇰🇼 Kuwait",
    phoneCode: "+965",
    currencyCode: "KWD",
    countryCode: "KW",
  },
  {
    value: "KG",
    label: "🇰🇬 Kyrgyzstan",
    phoneCode: "+996",
    currencyCode: "KGS",
    countryCode: "KG",
  },
  {
    value: "LA",
    label: "🇱🇦 Laos",
    phoneCode: "+856",
    currencyCode: "LAK",
    countryCode: "LA",
  },
  {
    value: "LV",
    label: "🇱🇻 Latvia",
    phoneCode: "+371",
    currencyCode: "EUR",
    countryCode: "LV",
  },
  {
    value: "LB",
    label: "🇱🇧 Lebanon",
    phoneCode: "+961",
    currencyCode: "LBP",
    countryCode: "LB",
  },
  {
    value: "LS",
    label: "🇱🇸 Lesotho",
    phoneCode: "+266",
    currencyCode: "LSL",
    countryCode: "LS",
  },
  {
    value: "LR",
    label: "🇱🇷 Liberia",
    phoneCode: "+231",
    currencyCode: "LRD",
    countryCode: "LR",
  },
  {
    value: "LY",
    label: "🇱🇾 Libya",
    phoneCode: "+218",
    currencyCode: "LYD",
    countryCode: "LY",
  },
  {
    value: "LI",
    label: "🇱🇮 Liechtenstein",
    phoneCode: "+423",
    currencyCode: "CHF",
    countryCode: "LI",
  },
  {
    value: "LT",
    label: "🇱🇹 Lithuania",
    phoneCode: "+370",
    currencyCode: "EUR",
    countryCode: "LT",
  },
  {
    value: "LU",
    label: "🇱🇺 Luxembourg",
    phoneCode: "+352",
    currencyCode: "EUR",
    countryCode: "LU",
  },
  {
    value: "MO",
    label: "🇲🇴 Macao",
    phoneCode: "+853",
    currencyCode: "MOP",
    countryCode: "MO",
  },
  {
    value: "MK",
    label: "🇲🇰 North Macedonia",
    phoneCode: "+389",
    currencyCode: "MKD",
    countryCode: "MK",
  },
  {
    value: "MG",
    label: "🇲🇬 Madagascar",
    phoneCode: "+261",
    currencyCode: "MGA",
    countryCode: "MG",
  },
  {
    value: "MW",
    label: "🇲🇼 Malawi",
    phoneCode: "+265",
    currencyCode: "MWK",
    countryCode: "MW",
  },
  {
    value: "MY",
    label: "🇲🇾 Malaysia",
    phoneCode: "+60",
    currencyCode: "MYR",
    countryCode: "MY",
  },
  {
    value: "MV",
    label: "🇲🇻 Maldives",
    phoneCode: "+960",
    currencyCode: "MVR",
    countryCode: "MV",
  },
  {
    value: "ML",
    label: "🇲🇱 Mali",
    phoneCode: "+223",
    currencyCode: "XOF",
    countryCode: "ML",
  },
  {
    value: "MT",
    label: "🇲🇹 Malta",
    phoneCode: "+356",
    currencyCode: "EUR",
    countryCode: "MT",
  },
  {
    value: "MH",
    label: "🇲🇭 Marshall Islands",
    phoneCode: "+692",
    currencyCode: "USD",
    countryCode: "MH",
  },
  {
    value: "MQ",
    label: "🇲🇶 Martinique",
    phoneCode: "+596",
    currencyCode: "EUR",
    countryCode: "MQ",
  },
  {
    value: "MR",
    label: "🇲🇷 Mauritania",
    phoneCode: "+222",
    currencyCode: "MRU",
    countryCode: "MR",
  },
  {
    value: "MU",
    label: "🇲🇺 Mauritius",
    phoneCode: "+230",
    currencyCode: "MUR",
    countryCode: "MU",
  },
  {
    value: "YT",
    label: "🇾🇹 Mayotte",
    phoneCode: "+262",
    currencyCode: "EUR",
    countryCode: "YT",
  },
  {
    value: "MX",
    label: "🇲🇽 Mexico",
    phoneCode: "+52",
    currencyCode: "MXN",
    countryCode: "MX",
  },
  {
    value: "FM",
    label: "🇫🇲 Micronesia",
    phoneCode: "+691",
    currencyCode: "USD",
    countryCode: "FM",
  },
  {
    value: "MD",
    label: "🇲🇩 Moldova",
    phoneCode: "+373",
    currencyCode: "MDL",
    countryCode: "MD",
  },
  {
    value: "MC",
    label: "🇲🇨 Monaco",
    phoneCode: "+377",
    currencyCode: "EUR",
    countryCode: "MC",
  },
  {
    value: "MN",
    label: "🇲🇳 Mongolia",
    phoneCode: "+976",
    currencyCode: "MNT",
    countryCode: "MN",
  },
  {
    value: "ME",
    label: "🇲🇪 Montenegro",
    phoneCode: "+382",
    currencyCode: "EUR",
    countryCode: "ME",
  },
  {
    value: "MS",
    label: "🇲🇸 Montserrat",
    phoneCode: "+1664",
    currencyCode: "XCD",
    countryCode: "MS",
  },
  {
    value: "MA",
    label: "🇲🇦 Morocco",
    phoneCode: "+212",
    currencyCode: "MAD",
    countryCode: "MA",
  },
  {
    value: "MZ",
    label: "🇲🇿 Mozambique",
    phoneCode: "+258",
    currencyCode: "MZN",
    countryCode: "MZ",
  },
  {
    value: "MM",
    label: "🇲🇲 Myanmar",
    phoneCode: "+95",
    currencyCode: "MMK",
    countryCode: "MM",
  },
  {
    value: "NA",
    label: "🇳🇦 Namibia",
    phoneCode: "+264",
    currencyCode: "NAD",
    countryCode: "NA",
  },
  {
    value: "NR",
    label: "🇳🇷 Nauru",
    phoneCode: "+674",
    currencyCode: "AUD",
    countryCode: "NR",
  },
  {
    value: "NP",
    label: "🇳🇵 Nepal",
    phoneCode: "+977",
    currencyCode: "NPR",
    countryCode: "NP",
  },
  {
    value: "NL",
    label: "🇳🇱 Netherlands",
    phoneCode: "+31",
    currencyCode: "EUR",
    countryCode: "NL",
  },
  {
    value: "NC",
    label: "🇳🇨 New Caledonia",
    phoneCode: "+687",
    currencyCode: "XPF",
    countryCode: "NC",
  },
  {
    value: "NZ",
    label: "🇳🇿 New Zealand",
    phoneCode: "+64",
    currencyCode: "NZD",
    countryCode: "NZ",
  },
  {
    value: "NI",
    label: "🇳🇮 Nicaragua",
    phoneCode: "+505",
    currencyCode: "NIO",
    countryCode: "NI",
  },
  {
    value: "NE",
    label: "🇳🇪 Niger",
    phoneCode: "+227",
    currencyCode: "XOF",
    countryCode: "NE",
  },
  {
    value: "NG",
    label: "🇳🇬 Nigeria",
    phoneCode: "+234",
    currencyCode: "NGN",
    countryCode: "NG",
  },
  { value: "NU", label: "🇳🇺 Niue", phoneCode: "+683", currencyCode: "NZD", countryCode: "NU" },
  {
    value: "NF",
    label: "🇳🇫 Norfolk Island",
    phoneCode: "+672",
    currencyCode: "AUD",
    countryCode: "NF",
  },
  {
    value: "MP",
    label: "🇲🇵 Northern Mariana Islands",
    phoneCode: "+1670",
    currencyCode: "USD",
    countryCode: "MP",
  },
  {
    value: "NO",
    label: "🇳🇴 Norway",
    phoneCode: "+47",
    currencyCode: "NOK",
    countryCode: "NO",
  },
  {
    value: "OM",
    label: "🇴🇲 Oman",
    phoneCode: "+968",
    currencyCode: "OMR",
    countryCode: "OM",
  },
  {
    value: "PK",
    label: "🇵🇰 Pakistan",
    phoneCode: "+92",
    currencyCode: "PKR",
    countryCode: "PK",
  },
  {
    value: "PW",
    label: "🇵🇼 Palau",
    phoneCode: "+680",
    currencyCode: "USD",
    countryCode: "PW",
  },
  {
    value: "PS",
    label: "🇵🇸 Palestine",
    phoneCode: "+970",
    currencyCode: "ILS",
    countryCode: "PS",
  },
  {
    value: "PA",
    label: "🇵🇦 Panama",
    phoneCode: "+507",
    currencyCode: "PAB",
    countryCode: "PA",
  },
  {
    value: "PG",
    label: "🇵🇬 Papua New Guinea",
    phoneCode: "+675",
    currencyCode: "PGK",
    countryCode: "PG",
  },
  {
    value: "PY",
    label: "🇵🇾 Paraguay",
    phoneCode: "+595",
    currencyCode: "PYG",
    countryCode: "PY",
  },
  {
    value: "PE",
    label: "🇵🇪 Peru",
    phoneCode: "+51",
    currencyCode: "PEN",
    countryCode: "PE",
  },
  {
    value: "PH",
    label: "🇵🇭 Philippines",
    phoneCode: "+63",
    currencyCode: "PHP",
    countryCode: "PH",
  },
  {
    value: "PN",
    label: "🇵🇳 Pitcairn",
    phoneCode: "+64",
    currencyCode: "NZD",
    countryCode: "PN",
  },
  {
    value: "PL",
    label: "🇵🇱 Poland",
    phoneCode: "+48",
    currencyCode: "PLN",
    countryCode: "PL",
  },
  {
    value: "PT",
    label: "🇵🇹 Portugal",
    phoneCode: "+351",
    currencyCode: "EUR",
    countryCode: "PT",
  },
  {
    value: "PR",
    label: "🇵🇷 Puerto Rico",
    phoneCode: "+1",
    currencyCode: "USD",
    countryCode: "PR",
  },
  {
    value: "QA",
    label: "🇶🇦 Qatar",
    phoneCode: "+974",
    currencyCode: "QAR",
    countryCode: "QA",
  },
  {
    value: "RE",
    label: "🇷🇪 Réunion",
    phoneCode: "+262",
    currencyCode: "EUR",
    countryCode: "RE",
  },
  {
    value: "RO",
    label: "🇷🇴 Romania",
    phoneCode: "+40",
    currencyCode: "RON",
    countryCode: "RO",
  },
  {
    value: "RU",
    label: "🇷🇺 Russia",
    phoneCode: "+7",
    currencyCode: "RUB",
    countryCode: "RU",
  },
  {
    value: "RW",
    label: "🇷🇼 Rwanda",
    phoneCode: "+250",
    currencyCode: "RWF",
    countryCode: "RW",
  },
  {
    value: "BL",
    label: "🇧🇱 Saint Barthélemy",
    phoneCode: "+590",
    currencyCode: "EUR",
    countryCode: "BL",
  },
  {
    value: "SH",
    label: "🇸🇭 Saint Helena",
    phoneCode: "+290",
    currencyCode: "SHP",
    countryCode: "SH",
  },
  {
    value: "KN",
    label: "🇰🇳 Saint Kitts and Nevis",
    phoneCode: "+1869",
    currencyCode: "XCD",
    countryCode: "KN",
  },
  {
    value: "LC",
    label: "🇱🇨 Saint Lucia",
    phoneCode: "+1758",
    currencyCode: "XCD",
    countryCode: "LC",
  },
  {
    value: "MF",
    label: "🇲🇫 Saint Martin",
    phoneCode: "+590",
    currencyCode: "EUR",
    countryCode: "MF",
  },
  {
    value: "PM",
    label: "🇵🇲 Saint Pierre and Miquelon",
    phoneCode: "+508",
    currencyCode: "EUR",
    countryCode: "PM",
  },
  {
    value: "VC",
    label: "🇻🇨 Saint Vincent and the Grenadines",
    phoneCode: "+1784",
    currencyCode: "STN",
    countryCode: "VC",
  },
  {
    value: "WS",
    label: "🇼🇸 Samoa",
    phoneCode: "+685",
    currencyCode: "WST",
    countryCode: "WS",
  },
  {
    value: "SM",
    label: "🇸🇲 San Marino",
    phoneCode: "+378",
    currencyCode: "EUR",
    countryCode: "SM",
  },
  {
    value: "ST",
    label: "🇸🇹 São Tomé and Príncipe",
    phoneCode: "+239",
    currencyCode: "STN",
    countryCode: "ST",
  },
  {
    value: "SA",
    label: "🇸🇦 Saudi Arabia",
    phoneCode: "+966",
    currencyCode: "SAR",
    countryCode: "SA",
  },
  {
    value: "SN",
    label: "🇸🇳 Senegal",
    phoneCode: "+221",
    currencyCode: "XOF",
    countryCode: "SN",
  },
  {
    value: "RS",
    label: "🇷🇸 Serbia",
    phoneCode: "+381",
    currencyCode: "RSD",
    countryCode: "RS",
  },
  {
    value: "SC",
    label: "🇸🇨 Seychelles",
    phoneCode: "+248",
    currencyCode: "SCR",
    countryCode: "SC",
  },
  {
    value: "SL",
    label: "🇸🇱 Sierra Leone",
    phoneCode: "+232",
    currencyCode: "SLE",
    countryCode: "SL",
  },
  {
    value: "SG",
    label: "🇸🇬 Singapore",
    phoneCode: "+65",
    currencyCode: "SGD",
    countryCode: "SG",
  },
  {
    value: "SX",
    label: "🇸🇽 Sint Maarten",
    phoneCode: "+1721",
    currencyCode: "ANG",
    countryCode: "SX",
  },
  {
    value: "SK",
    label: "🇸🇰 Slovakia",
    phoneCode: "+421",
    currencyCode: "EUR",
    countryCode: "SK",
  },
  {
    value: "SI",
    label: "🇸🇮 Slovenia",
    phoneCode: "+386",
    currencyCode: "EUR",
    countryCode: "SI",
  },
  {
    value: "SB",
    label: "🇸🇧 Solomon Islands",
    phoneCode: "+677",
    currencyCode: "SBD",
    countryCode: "SB",
  },
  {
    value: "SO",
    label: "🇸🇴 Somalia",
    phoneCode: "+252",
    currencyCode: "SOS",
    countryCode: "SO",
  },
  {
    value: "ZA",
    label: "🇿🇦 South Africa",
    phoneCode: "+27",
    currencyCode: "ZAR",
    countryCode: "ZA",
  },
  {
    value: "GS",
    label: "🇬🇸 South Georgia and the South Sandwich Islands",
    phoneCode: "+500",
    currencyCode: "GBP",
    countryCode: "GS",
  },
  {
    value: "SS",
    label: "🇸🇸 South Sudan",
    phoneCode: "+211",
    currencyCode: "SSP",
    countryCode: "SS",
  },
  {
    value: "ES",
    label: "🇪🇸 Spain",
    phoneCode: "+34",
    currencyCode: "EUR",
    countryCode: "ES",
  },
  {
    value: "LK",
    label: "🇱🇰 Sri Lanka",
    phoneCode: "+94",
    currencyCode: "LKR",
    countryCode: "LK",
  },
  {
    value: "SD",
    label: "🇸🇩 Sudan",
    phoneCode: "+249",
    currencyCode: "SDG",
    countryCode: "SD",
  },
  {
    value: "SR",
    label: "🇸🇷 Suriname",
    phoneCode: "+597",
    currencyCode: "SRD",
    countryCode: "SR",
  },
  {
    value: "SJ",
    label: "🇸🇯 Svalbard and Jan Mayen",
    phoneCode: "+47",
    currencyCode: "NOK",
    countryCode: "SJ",
  },
  {
    value: "SE",
    label: "🇸🇪 Sweden",
    phoneCode: "+46",
    currencyCode: "SEK",
    countryCode: "SE",
  },
  {
    value: "CH",
    label: "🇨🇭 Switzerland",
    phoneCode: "+41",
    currencyCode: "CHF",
    countryCode: "CH",
  },
  {
    value: "SY",
    label: "🇸🇾 Syria",
    phoneCode: "+963",
    currencyCode: "SYP",
    countryCode: "SY",
  },
  {
    value: "TW",
    label: "🇹🇼 Taiwan",
    phoneCode: "+886",
    currencyCode: "TWD",
    countryCode: "TW",
  },
  {
    value: "TJ",
    label: "🇹🇯 Tajikistan",
    phoneCode: "+992",
    currencyCode: "TJS",
    countryCode: "TJ",
  },
  {
    value: "TZ",
    label: "🇹🇿 Tanzania",
    phoneCode: "+255",
    currencyCode: "TZS",
    countryCode: "TZ",
  },
  {
    value: "TH",
    label: "🇹🇭 Thailand",
    phoneCode: "+66",
    currencyCode: "THB",
    countryCode: "TH",
  },
  {
    value: "TL",
    label: "🇹🇱 Timor-Leste",
    phoneCode: "+670",
    currencyCode: "USD",
    countryCode: "TL",
  },
  {
    value: "TG",
    label: "🇹🇬 Togo",
    phoneCode: "+228",
    currencyCode: "XOF",
    countryCode: "TG",
  },
  { value: "TK", label: "🇹🇰 Tokelau", phoneCode: "+690", currencyCode: "NZD", countryCode: "TK" },
  {
    value: "TO",
    label: "🇹🇴 Tonga",
    phoneCode: "+676",
    currencyCode: "TOP",
    countryCode: "TO",
  },
  {
    value: "TT",
    label: "🇹🇹 Trinidad and Tobago",
    phoneCode: "+1868",
    currencyCode: "TTD",
    countryCode: "TT",
  },
  {
    value: "TN",
    label: "🇹🇳 Tunisia",
    phoneCode: "+216",
    currencyCode: "TND",
    countryCode: "TN",
  },
  {
    value: "TR",
    label: "🇹🇷 Turkey",
    phoneCode: "+90",
    currencyCode: "TRY",
    countryCode: "TR",
  },
  {
    value: "TM",
    label: "🇹🇲 Turkmenistan",
    phoneCode: "+993",
    currencyCode: "TMT",
    countryCode: "TM",
  },
  {
    value: "TC",
    label: "🇹🇨 Turks and Caicos Islands",
    phoneCode: "+1649",
    currencyCode: "USD",
    countryCode: "TC",
  },
  {
    value: "TV",
    label: "🇹🇻 Tuvalu",
    phoneCode: "+688",
    currencyCode: "AUD",
    countryCode: "TV",
  },
  {
    value: "UG",
    label: "🇺🇬 Uganda",
    phoneCode: "+256",
    currencyCode: "UGX",
    countryCode: "UG",
  },
  {
    value: "UA",
    label: "🇺🇦 Ukraine",
    phoneCode: "+380",
    currencyCode: "UAH",
    countryCode: "UA",
  },
  {
    value: "AE",
    label: "🇦🇪 United Arab Emirates",
    phoneCode: "+971",
    currencyCode: "AED",
    countryCode: "AE",
  },
  {
    value: "GB",
    label: "🇬🇧 United Kingdom",
    phoneCode: "+44",
    currencyCode: "GBP",
    countryCode: "GB",
  },
  {
    value: "US",
    label: "🇺🇸 United States",
    phoneCode: "+1",
    currencyCode: "USD",
    countryCode: "US",
  },
  {
    value: "UM",
    label: "🇺🇲 United States Minor Outlying Islands",
    phoneCode: "+1",
    currencyCode: "USD",
    countryCode: "UM",
  },
  {
    value: "UY",
    label: "🇺🇾 Uruguay",
    phoneCode: "+598",
    currencyCode: "UYU",
    countryCode: "UY",
  },
  {
    value: "UZ",
    label: "🇺🇿 Uzbekistan",
    phoneCode: "+998",
    currencyCode: "UZS",
    countryCode: "UZ",
  },
  {
    value: "VU",
    label: "🇻🇺 Vanuatu",
    phoneCode: "+678",
    currencyCode: "VUV",
    countryCode: "VU",
  },
  {
    value: "VE",
    label: "🇻🇪 Venezuela",
    phoneCode: "+58",
    currencyCode: "VES",
    countryCode: "VE",
  },
  {
    value: "VN",
    label: "🇻🇳 Vietnam",
    phoneCode: "+84",
    currencyCode: "VND",
    countryCode: "VN",
  },
  {
    value: "VG",
    label: "🇻🇬 British Virgin Islands",
    phoneCode: "+1284",
    currencyCode: "USD",
    countryCode: "VG",
  },
  {
    value: "VI",
    label: "🇻🇮 U.S. Virgin Islands",
    phoneCode: "+1340",
    currencyCode: "USD",
    countryCode: "VI",
  },
  {
    value: "WF",
    label: "🇼🇫 Wallis and Futuna",
    phoneCode: "+681",
    currencyCode: "XPF",
    countryCode: "WF",
  },
  {
    value: "EH",
    label: "🇪🇭 Western Sahara",
    phoneCode: "+212",
    currencyCode: "MAD",
    countryCode: "EH",
  },
  {
    value: "YE",
    label: "🇾🇪 Yemen",
    phoneCode: "+967",
    currencyCode: "YER",
    countryCode: "YE",
  },
  {
    value: "ZM",
    label: "🇿🇲 Zambia",
    phoneCode: "+260",
    currencyCode: "ZMW",
    countryCode: "ZM",
  },
  {
    value: "ZW",
    label: "🇿🇼 Zimbabwe",
    phoneCode: "+263",
    currencyCode: "ZWL",
    countryCode: "ZW",
  },
]
